language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t harrydu/react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true harrydu/react-test npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-112346008503"
  bucket_path: "docker"
  on:
    branch: master
access_key_id: $AWA_ACCESS_KEY
secret_access_key: $AWS_SECRET_KET
